include:
  - template: Auto-DevOps.gitlab-ci.yml
  
variables:
  SAST_DISABLED: "true"
  LICENSE_MANAGEMENT_DISABLED: "true"
  DEPENDENCY_SCANNING_DISABLED: "true"
  DAST_DISABLED: "true"
  CONTAINER_SCANNING_DISABLED: "true"
  CODE_QUALITY_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"
